version: "3.9"
services:
  frontend:
    image: ghcr.io/esir2-projet-keolis/frontend:master
    depends_on:
      - backend
    ports:
      - "3000:3000"
  backend:
    image: ghcr.io/esir2-projet-keolis/backend:main
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_HOST: cache
      API_PROCESSUNIT: processingunit:8090
  collector:
    image: ghcr.io/esir2-projet-keolis/collector:main
    depends_on:
      - rabbitmq
    environment:
      - PROD=True
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - "15672:15672"
  processingunit:
    image: ghcr.io/esir2-projet-keolis/processing-storage-unit:master
    depends_on:
      - rabbitmq
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
  db:
    image: ghcr.io/esir2-projet-keolis/mysql-db:main
  cache:
    image: redis:alpine3.17
    restart: always

  API_IA:
    image: ghcr.io/esir2-projet-keolis/ia_api:main
    ports:
      - "5001:5001"
