version: "3.9"
services:
  frontend:
    image: ghcr.io/esir2-projet-keolis/frontend:sprint1
    depends_on:
      - backend
    ports:
      - "3000:3000"
  backend:
    image: ghcr.io/esir2-projet-keolis/backend:main
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "4000:4000"
      - "3500:3500"
  collector:
    image: ghcr.io/esir2-projet-keolis/collector:ProdDevAndFixBug
    depends_on:
      - rabbitmq
    environment:
      - PROD=True
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
  processingunit:
    image: ghcr.io/esir2-projet-keolis/processing-storage-unit:master
    depends_on:
      - rabbitmq